apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hpa-demo
    spec:
      containers:
        - name: hpa-example
          image: gopimanchu9/servervmetrics
          ports:
            - containerPort: 80
              name: http-port
          resources:
            requests:
              cpu: 200m
  selector:
    matchLabels:
      app: hpa-demo